[package]
edition = "2018"
name = "sirwindfield_common-user-folders"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
directories-next = "2.0.0"
napi = "1"
napi-derive = "1"
paste = "1.0.4"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
